//1652437926000000000
//Please, do not change the line above
/*
 * This file is automatically generated by UnitTestBot. For further information see https://github.com/UnitTestBot/UTBotCpp
 * Copyright (c) Huawei Technologies Co., Ltd. 2012-2021. All rights reserved.
 */

#define _Alignas(x)
typedef long ptrdiff_t;

typedef unsigned long size_t;

typedef struct {
    long long __clang_max_align_nonce1 __attribute__((aligned(__alignof(long long))));
    long double __clang_max_align_nonce2 __attribute__((aligned(__alignof(long double))));
} max_align_t;

typedef unsigned int typedef_from_c;

typedef int typedef_from_c_param;


